#!/usr/bin/env bash
#
# One-time bootstrap for the JevMed ERP on a fresh Hostinger VPS (Ubuntu/Debian).
# Safe to run more than once: every step checks before it acts.
#
#   curl -fsSL https://raw.githubusercontent.com/<you>/jevmed-erp/main/deploy/setup-vps.sh -o setup-vps.sh
#   sudo bash setup-vps.sh
#
# What it does:
#   · installs Node 22, nginx and certbot if they are missing
#   · creates the jevmed service account and /opt/jevmed
#   · generates the unlisted key-console path and the encryption key
#   · asks you for the vault passphrase and stores only its hash
#   · installs the systemd unit and nginx vhost
#   · obtains the TLS certificate for jevmed.trilumi.xyz
#
set -euo pipefail

DOMAIN="${DOMAIN:-jevmed.trilumi.xyz}"
APP_DIR="${APP_DIR:-/opt/jevmed}"
APP_USER="${APP_USER:-jevmed}"
DEPLOY_USER="${DEPLOY_USER:-$(logname 2>/dev/null || echo root)}"
NODE_MAJOR=22
PORT=8787

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
step() { printf '\n\033[1;34m▸ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m  ! %s\033[0m\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { echo "Run this with sudo." >&2; exit 1; }

step "Checking packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
for pkg in curl ca-certificates gnupg rsync ufw; do
  dpkg -s "$pkg" >/dev/null 2>&1 || apt-get install -y -qq "$pkg"
done

if ! command -v node >/dev/null 2>&1 || [ "$(node -v | sed 's/v\([0-9]*\).*/\1/')" -lt "$NODE_MAJOR" ]; then
  bold "Installing Node.js ${NODE_MAJOR}"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y -qq nodejs
fi
echo "  node $(node -v), npm $(npm -v)"

command -v nginx >/dev/null 2>&1 || apt-get install -y -qq nginx
command -v certbot >/dev/null 2>&1 || apt-get install -y -qq certbot python3-certbot-nginx

step "Creating the service account and directories"
id -u "$APP_USER" >/dev/null 2>&1 || useradd --system --home "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"
mkdir -p "$APP_DIR/releases" "$APP_DIR/shared/data"
# The deploy user writes releases; the service account reads them and owns the
# vault directory. Nothing in this tree is world-readable.
chown -R "$DEPLOY_USER":"$APP_USER" "$APP_DIR"
chown -R "$APP_USER":"$APP_USER" "$APP_DIR/shared/data"
chmod 750 "$APP_DIR"
chmod 700 "$APP_DIR/shared/data"

step "Configuring the environment"
ENV_FILE="$APP_DIR/shared/.env"
if [ -f "$ENV_FILE" ]; then
  warn "$ENV_FILE already exists — leaving it untouched."
  warn "Delete it and re-run this script if you want fresh secrets."
else
  VAULT_PATH="ops-$(openssl rand -hex 24)"
  MASTER_KEY="$(openssl rand -hex 32)"

  echo
  bold "Choose the passphrase that unlocks the key-management console."
  bold "It is never stored — only a scrypt hash of it is."
  while :; do
    read -rsp "  Passphrase (16+ characters): " PASS1; echo
    read -rsp "  Repeat: " PASS2; echo
    [ "$PASS1" = "$PASS2" ] || { warn "They do not match."; continue; }
    [ "${#PASS1}" -ge 16 ] || { warn "Too short — use at least 16 characters."; continue; }
    break
  done

  # Hash it with the application's own function so the format always matches.
  HASH="$(cd "$APP_DIR/current" 2>/dev/null && node server/hash-passphrase.js "$PASS1" 2>/dev/null || true)"
  if [ -z "$HASH" ]; then
    warn "The application is not deployed yet, so the passphrase hash cannot be"
    warn "generated here. Run this on the VPS after the first deploy:"
    warn "    cd $APP_DIR/current && node server/hash-passphrase.js 'your passphrase'"
    warn "then paste the result into VAULT_PASSPHRASE_HASH in $ENV_FILE."
    HASH="PASTE_THE_HASH_HERE"
  fi
  unset PASS1 PASS2

  cat > "$ENV_FILE" <<ENVEOF
# JevMed ERP — generated by setup-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of version control. Losing VAULT_MASTER_KEY only means
# re-entering the provider API key; losing this whole file means regenerating
# the console path as well.
PORT=$PORT
PUBLIC_ORIGIN=https://$DOMAIN
DATA_DIR=$APP_DIR/shared/data
VAULT_PATH=$VAULT_PATH
VAULT_MASTER_KEY=$MASTER_KEY
VAULT_PASSPHRASE_HASH=$HASH
ENVEOF
  chown "$APP_USER":"$APP_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"

  echo
  bold "════════════════════════════════════════════════════════════════════"
  bold " Key-management console — write this down now, it is not shown again"
  bold "════════════════════════════════════════════════════════════════════"
  echo "   https://$DOMAIN/$VAULT_PATH"
  bold "════════════════════════════════════════════════════════════════════"
  echo
fi

step "Installing the systemd unit"
UNIT_SRC="$(dirname "$0")/jevmed.service"
[ -f "$UNIT_SRC" ] || UNIT_SRC="$APP_DIR/current/deploy/jevmed.service"
if [ -f "$UNIT_SRC" ]; then
  sed -e "s#/opt/jevmed#$APP_DIR#g" -e "s#^User=.*#User=$APP_USER#" -e "s#^Group=.*#Group=$APP_USER#" \
      "$UNIT_SRC" > /etc/systemd/system/jevmed.service
  systemctl daemon-reload
  systemctl enable jevmed >/dev/null 2>&1 || true
  echo "  installed /etc/systemd/system/jevmed.service"
else
  warn "jevmed.service not found — copy deploy/jevmed.service to /etc/systemd/system/ manually."
fi

step "Granting the deploy user permission to restart the service"
# The only privileged action CI performs. Nothing broader is granted.
cat > /etc/sudoers.d/jevmed-deploy <<SUDOEOF
$DEPLOY_USER ALL=(root) NOPASSWD: /bin/systemctl restart jevmed, /bin/systemctl status jevmed, /usr/bin/journalctl -u jevmed *
SUDOEOF
chmod 440 /etc/sudoers.d/jevmed-deploy
visudo -cf /etc/sudoers.d/jevmed-deploy >/dev/null && echo "  sudoers rule installed for $DEPLOY_USER"

step "Configuring nginx"
VHOST_SRC="$(dirname "$0")/nginx-jevmed.conf"
[ -f "$VHOST_SRC" ] || VHOST_SRC="$APP_DIR/current/deploy/nginx-jevmed.conf"
if [ -f "$VHOST_SRC" ] && [ ! -f "/etc/nginx/sites-available/$DOMAIN" ]; then
  sed "s/jevmed.trilumi.xyz/$DOMAIN/g" "$VHOST_SRC" > "/etc/nginx/sites-available/$DOMAIN"
  ln -sfn "/etc/nginx/sites-available/$DOMAIN" "/etc/nginx/sites-enabled/$DOMAIN"
  nginx -t && systemctl reload nginx
  echo "  vhost installed for $DOMAIN"
else
  warn "nginx vhost already present or source missing — skipping."
fi

step "Firewall"
if command -v ufw >/dev/null 2>&1; then
  ufw allow OpenSSH >/dev/null 2>&1 || true
  ufw allow 'Nginx Full' >/dev/null 2>&1 || true
  echo "  ports 22, 80 and 443 allowed (enable with: ufw enable)"
fi

step "TLS certificate"
if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
  echo "  certificate already present; certbot renews it automatically"
else
  RESOLVED="$(getent hosts "$DOMAIN" | awk '{print $1}' | head -1 || true)"
  MYIP="$(curl -fsS https://api.ipify.org 2>/dev/null || true)"
  if [ -z "$RESOLVED" ]; then
    warn "$DOMAIN does not resolve yet."
    warn "Add this A record in Hostinger hPanel → Domains → DNS, then re-run:"
    warn "    Type A · Name jevmed · Points to ${MYIP:-<this server IP>} · TTL 300"
  elif [ -n "$MYIP" ] && [ "$RESOLVED" != "$MYIP" ]; then
    warn "$DOMAIN resolves to $RESOLVED but this server is $MYIP."
    warn "Fix the A record and re-run, or certbot will fail the challenge."
  else
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
      --register-unsafely-without-email --redirect || \
      warn "certbot failed — run it by hand: certbot --nginx -d $DOMAIN"
  fi
fi

step "Done"
cat <<SUMMARY

  Application directory  $APP_DIR
  Service account        $APP_USER
  Deploy user            $DEPLOY_USER
  Environment file       $APP_DIR/shared/.env
  Vault (encrypted)      $APP_DIR/shared/data/vault.enc

  Next:
    1. Add these GitHub repository secrets:
         VPS_HOST      this server's IP or hostname
         VPS_USER      $DEPLOY_USER
         VPS_SSH_KEY   the PRIVATE key whose public half is in
                       ~$DEPLOY_USER/.ssh/authorized_keys
         VPS_SSH_PORT  22 (or your custom port)
         VPS_APP_DIR   $APP_DIR
    2. Push to main. The workflow builds, verifies and deploys.
    3. Open the key-management console URL printed above and add the API key.

SUMMARY
